logging:
  file:
    name: logs/gateway.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    org.msa.itemservice: debug

spring:
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/v1/item/**
            - Path=/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka